#!/bin/bash
set -e

RELEASE_ENVS=(
    tdeck
    cardputer-cap
    tlora-pager-tft
)

OTA_SIGNING_KEY_PATH=${PLUMERIA_OTA_SIGNING_KEY:-}

env_out_name() {
    case "$1" in
        *)                            echo "$1" ;;
    esac
}

env_flash_size() {
    case "$1" in
        cardputer-cap) echo "8MB" ;;
        *)             echo "16MB" ;;
    esac
}

has_env() {
    local env_name="$1"
    grep -q "^\[env:${env_name}\]" platformio.ini
}

require_cmd() {
    local cmd="$1"
    local name="$2"
    if ! command -v "$cmd" >/dev/null 2>&1; then
        echo "Error: ${name} is required but not installed." >&2
        exit 1
    fi
}

write_ota_pubkey_header() {
    local key_path="$1"
    local tmp_pub
    tmp_pub=$(mktemp)

    openssl pkey -in "$key_path" -pubout -out "$tmp_pub"

    {
        echo "#pragma once"
        echo ""
        echo "namespace plumeria {"
        echo "namespace ota {"
        echo ""
        echo "// Auto-generated by release.sh from PLUMERIA_OTA_SIGNING_KEY."
        echo "constexpr const char kOtaSigningPublicKeyPem[] ="
        while IFS= read -r line; do
            printf '    "%s\\n"\n' "$line"
        done < "$tmp_pub"
        echo "    ;"
        echo ""
        echo "}  // namespace ota"
        echo "}  // namespace plumeria"
    } > src/ota/ota_signing_pubkey.h

    rm -f "$tmp_pub"
}

clear_previous_builds() {
    echo "Clearing previous build artifacts..."

    rm -rf .pio/build
    rm -rf dist

    if [[ -d builds ]]; then
        find builds -mindepth 1 ! -name ".gitkeep" -exec rm -rf {} +
    fi

    echo "Previous build artifacts cleared."
}

remote_tag_exists() {
    local tag="$1"
    git ls-remote --tags origin | grep -q "refs/tags/${tag}$"
}

delete_existing_release_and_tags() {
    local tag="$1"
    local remote_exists=false

    echo "Tag ${tag} already exists. Deleting existing release/tag so it can be recreated..."

    if remote_tag_exists "$tag"; then
        remote_exists=true
    fi

    if command -v gh >/dev/null 2>&1; then
        if gh release view "$tag" >/dev/null 2>&1; then
            gh release delete "$tag" --yes
            echo "Deleted existing GitHub release ${tag}."
        else
            echo "No existing GitHub release for ${tag}."
        fi
    elif [[ "$remote_exists" == true ]]; then
        echo "GitHub CLI (gh) is required to delete an existing GitHub release for ${tag}."
        echo "Install gh or manually delete the release, then rerun."
        exit 1
    fi

    if [[ "$remote_exists" == true ]]; then
        git push origin ":refs/tags/${tag}"
        echo "Deleted remote tag ${tag}."
    fi

    if git tag | grep -q "^${tag}$"; then
        git tag -d "$tag"
        echo "Deleted local tag ${tag}."
    fi
}

CURRENT=$(cat VERSION 2>/dev/null | tr -d '\n')
PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "none")
echo "Current version: ${CURRENT:-unknown}"
echo "Latest git tag:  $PREV_TAG"
echo ""
read -rp "New version (e.g. 1.0.0): " VERSION

if [[ -z "$VERSION" ]]; then
    echo "No version entered. Aborting."
    exit 1
fi

if [[ -z "$OTA_SIGNING_KEY_PATH" ]]; then
    echo "Error: PLUMERIA_OTA_SIGNING_KEY is not set." >&2
    echo "Set it to a PEM private key path used to sign OTA assets." >&2
    exit 1
fi
if [[ ! -f "$OTA_SIGNING_KEY_PATH" ]]; then
    echo "Error: signing key not found at '$OTA_SIGNING_KEY_PATH'." >&2
    exit 1
fi

require_cmd openssl "OpenSSL"
require_cmd gh "GitHub CLI (gh)"

echo "Generating OTA public key header from signing key..."
write_ota_pubkey_header "$OTA_SIGNING_KEY_PATH"

TAG="v$VERSION"

# Recreate existing release/tag when rerunning a version
if remote_tag_exists "$TAG" || git tag | grep -q "^${TAG}$"; then
    delete_existing_release_and_tags "$TAG"
fi

# Update VERSION file
echo "$TAG" > VERSION
echo "Updated VERSION to $TAG"

# Build firmware
clear_previous_builds

echo "Building firmware..."
BUILD_ARGS=()
for env_name in "${RELEASE_ENVS[@]}"; do
    if has_env "$env_name"; then
        BUILD_ARGS+=( -e "$env_name" )
    fi
done

if [[ ${#BUILD_ARGS[@]} -eq 0 ]]; then
    echo "No release environments found in platformio.ini"
    exit 1
fi

~/.platformio/penv/bin/pio run "${BUILD_ARGS[@]}"
echo "Build successful."

# Resolve toolchain assets needed for factory image merge.
BOOT_APP0=$(find ~/.platformio/packages/framework-arduinoespressif32/tools/partitions \
    -name boot_app0.bin 2>/dev/null | head -1)
if [[ -z "$BOOT_APP0" ]]; then
    echo "Error: boot_app0.bin not found in PlatformIO packages." >&2
    echo "Run 'pio run' once to install framework assets." >&2
    exit 1
fi

if python -m esptool version >/dev/null 2>&1; then
    ESPTOOL="python -m esptool"
elif command -v esptool.py >/dev/null 2>&1; then
    ESPTOOL="esptool.py"
else
    echo "Error: esptool not found. Run: pip install esptool" >&2
    exit 1
fi

# Stage release artifacts
echo "Staging release artifacts to dist/..."
mkdir -p dist

for env_name in "${RELEASE_ENVS[@]}"; do
    if ! has_env "$env_name"; then
        continue
    fi

    build_dir=".pio/build/${env_name}"
    out_name="$(env_out_name "$env_name")"
    flash_size="$(env_flash_size "$env_name")"

    if [[ ! -f "${build_dir}/firmware.bin" ]]; then
        echo "Warning: ${build_dir}/firmware.bin not found, skipping ${env_name}."
        continue
    fi

    factory_out="dist/plumeria-mc-${out_name}-${TAG}.bin"
    ota_out="dist/plumeria-mc-${out_name}-${TAG}-ota.bin"

    $ESPTOOL --chip esp32s3 merge_bin \
        --output "${factory_out}" \
        --flash_mode dio \
        --flash_freq 80m \
        --flash_size "${flash_size}" \
        0x0     "${build_dir}/bootloader.bin" \
        0x8000  "${build_dir}/partitions.bin" \
        0xe000  "${BOOT_APP0}" \
        0x10000 "${build_dir}/firmware.bin"

    cp "${build_dir}/firmware.bin" "${ota_out}"

    if [[ -f "${build_dir}/firmware.elf" ]]; then
        cp "${build_dir}/firmware.elf" "dist/plumeria-mc-${out_name}-${TAG}.elf"
    fi
done

echo "Artifacts staged:"
ls -lh dist/

echo "Signing firmware assets..."
SIGNED_COUNT=0
for asset in dist/*.bin; do
    [[ -f "$asset" ]] || continue
    openssl dgst -sha256 -sign "$OTA_SIGNING_KEY_PATH" -out "${asset}.sig" "$asset"
    SIGNED_COUNT=$((SIGNED_COUNT + 1))
done

if [[ "$SIGNED_COUNT" -eq 0 ]]; then
    echo "Error: no firmware .bin assets found to sign." >&2
    exit 1
fi

echo "Generated signatures:"
ls -lh dist/*.sig

# Commit and push all changes
git add -A
git commit -m "Release $TAG"
git push

echo "Changes committed and pushed."

# Remove stale local tag if present
if git tag | grep -q "^$TAG$"; then
    git tag -d "$TAG"
fi

git tag "$TAG"
git push origin "$TAG"

echo "Publishing GitHub release assets..."
if gh release view "$TAG" >/dev/null 2>&1; then
    gh release upload "$TAG" dist/* --clobber
else
    gh release create "$TAG" dist/* --latest --generate-notes
fi

echo "Release published with signed assets: https://github.com/oumike/plumeria-mc/releases/tag/$TAG"
