#pragma once

namespace plumeria {
namespace ota {

// Auto-generated by release.sh from PLUMERIA_OTA_SIGNING_KEY.
constexpr const char kOtaSigningPublicKeyPem[] =
    "-----BEGIN PUBLIC KEY-----\n"
    "MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEiRPIGApb6inoZNZNsmnDydQELhdx\n"
    "lPplsHQ8jOmqk9wyMdAt5u/JosEcnpZhrAcH0xmEY/JfrI2+8d3kyyu1tw==\n"
    "-----END PUBLIC KEY-----\n"
    ;

}  // namespace ota
}  // namespace plumeria
